services:
  postgres:
    image: postgres:18
    container_name: postgres18
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - application_network

volumes:
  postgres_data:

networks:
  application_network:
    driver: bridge
